-- ==============================================================================
-- Supabase Schema for English Lab Consultancy
-- Tables: contact_form & study_materials
-- Run this in your Supabase Project Dashboard -> SQL Editor -> New Query
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. CONTACT FORM TABLE & POLICIES
-- ------------------------------------------------------------------------------

create table if not exists public.contact_form (
  id int8 generated by default as identity primary key,
  fullname text not null,
  email varchar not null,
  phone numeric not null,
  reason varchar not null,
  message varchar not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table public.contact_form enable row level security;

-- Drop policy if it already exists, then create the policy allowing public submissions
drop policy if exists "Allow public to insert contact forms" on public.contact_form;
create policy "Allow public to insert contact forms"
  on public.contact_form
  for insert
  to anon, authenticated
  with check (true);

-- (Optional) Only authenticated admins can read submitted messages
drop policy if exists "Allow authenticated admins to read contact forms" on public.contact_form;
create policy "Allow authenticated admins to read contact forms"
  on public.contact_form
  for select
  to authenticated
  using (true);

-- ------------------------------------------------------------------------------
-- 2. STUDY MATERIALS TABLE & POLICIES
-- ------------------------------------------------------------------------------

create table if not exists public.study_materials (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text unique,
  description text,
  category text,
  level text default 'All Levels',
  pages integer default 0,
  format text default 'PDF',
  price numeric default 0,
  price_formatted text default 'FREE',
  is_free boolean default false,
  featured boolean default false,
  thumbnail text,
  file_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.study_materials enable row level security;

-- Create public read-only policy for anon/authenticated users
drop policy if exists "Allow public read-only access to study materials" on public.study_materials;
create policy "Allow public read-only access to study materials"
  on public.study_materials
  for select
  using (true);

-- Seed initial publications
insert into public.study_materials (
  title,
  slug,
  description,
  category,
  level,
  pages,
  format,
  price,
  price_formatted,
  is_free,
  featured,
  thumbnail
)
values
  (
    'The Comprehensive English Grammar & Syntax Handbook',
    'comprehensive-english-grammar-syntax-handbook',
    'A systematic masterclass in sentence structure, subject-verb agreement, clauses, and common grammatical pitfalls.',
    'Grammar & Syntax',
    'Intermediate',
    68,
    'PDF',
    5000,
    '₦5,000',
    false,
    true,
    'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=800&q=80'
  ),
  (
    'UTME & SSCE Use of English Master Strategy Guide',
    'utme-ssce-use-of-english-master-strategy-guide',
    'High-yield analysis of past questions, lexis and structure patterns, antonyms/synonyms, and time-saving test strategies.',
    'Exam Preparation',
    'Intermediate',
    94,
    'PDF',
    4500,
    '₦4,500',
    false,
    true,
    'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=800&q=80'
  ),
  (
    'Essential Foundations: 100 Common English Errors to Avoid',
    '100-common-english-errors-to-avoid',
    'A concise diagnostic guide highlighting the most frequent everyday spoken and written errors, with direct corrections.',
    'Grammar & Syntax',
    'Beginner',
    32,
    'PDF',
    0,
    'FREE',
    true,
    true,
    'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=800&q=80'
  ),
  (
    'The Professional Email & Business Correspondence Playbook',
    'professional-email-business-correspondence-playbook',
    'Frameworks, high-impact templates, and etiquette guides for persuasive workplace emails, proposals, and briefings.',
    'Business Communication',
    'Intermediate',
    54,
    'PDF',
    6000,
    '₦6,000',
    false,
    false,
    'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80'
  ),
  (
    'Mastering Spoken Diction & Eloquence: Accent & Articulation',
    'mastering-spoken-diction-eloquence',
    'A comprehensive guide to vocal clarity, phonetic articulation, syllable stress, and commanding speech presence.',
    'Speaking & Eloquence',
    'Advanced',
    48,
    'PDF',
    5500,
    '₦5,500',
    false,
    false,
    'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=800&q=80'
  )
on conflict (slug) do nothing;
